# Generated by Django 5.2.3 on 2025-07-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-date_sent'], 'verbose_name': 'Contact Message', 'verbose_name_plural': 'Contact Messages'},
        ),
        migrations.AlterModelOptions(
            name='newslettersubscriber',
            options={'ordering': ['-subscribed_at'], 'verbose_name': 'Newsletter Subscriber', 'verbose_name_plural': 'Newsletter Subscribers'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-paid_at'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterField(
            model_name='payment',
            name='product_type',
            field=models.CharField(choices=[('signal_monthly', 'Monthly Signal'), ('signal_yearly', 'Yearly Signal'), ('signal_lifetime', 'Lifetime Signal'), ('mentorship_online', 'Online Mentorship'), ('mentorship_physical', 'Physical Mentorship'), ('mentorship_private', 'Private Mentorship')], max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
